logging:
  level: INFO
  loggers:
    cdk.personal.repo: INFO

swagger:
  resourcePackage: cdk.personal.repo.resources
  title: LifeWay Word Count API
  version: 1.0-SNAPSHOT
  description: This service receives an id and message and returns a cumulative count of all words in the messages from distinct ids.